dist: xenial
language: python
python:
  - 3.7

sudo: required

services:
  - docker

before_install:
  # Shut down postgres because it blocks our db container's port map to :5432
  - sudo service postgresql stop
  # Wait for it to stop
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
  # Setup shell environment
  - source env.template
  # Create fake usb device node to make api container happy
  - sudo mkdir -p /dev/bus/usb/001
  - sudo mknod /dev/bus/usb/001/001 c 189 260

install:
  - MOCK_RADIO=1 docker-compose up --build -d

before_script:
  - python3 -m pip install --upgrade pip
  - pip install -r ./src/requirements-dev.txt

script:
  - black --check ./src
  - tox -c ./src/tox.ini -e coverage
  - tox -c ./src/tox.ini -e oauth
  - docker-compose logs
  - docker ps | grep api | grep -q healthy
