stepped_frequency_time_domain_iq:
  name: survey_700MHz_band_40dB_80ms_iq
  fcs:
    - 700.5e6
    - 709e6
    - 731.5e6
    - 739e6
    - 751e6
    - 763e6
    - 772e6
    - 782e6
    - 793e6
    - 802e6
  gains:
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
  sample_rates:
    - 15.36e6
    - 15.36e6
    - 15.36e6
    - 15.36e6
    - 15.36e6
    - 15.36e6
    - 15.36e6
    - 15.36e6
    - 15.36e6
    - 15.36e6
  durations_ms:
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
